import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  whitepaperSidebar: [{type: 'autogenerated', dirName: '.'}],
  pitchdeckSidebar: [{type: 'autogenerated', dirName: '.'}],
  blogSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
